###
POST http://localhost:3003/api/users/
Content-Type: application/json
Authorization: 

{
  "username": "ahellas",
  "name": "Arto Hellas",
  "password": "123456"
}

###
POST http://localhost:3003/api/users/
Content-Type: application/json
Authorization: 

{
  "username": "ml",
  "name": "Matti",
  "password": "123"
}

###
POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MmI2ZGM2OTA0ZGFhZjc1MzcxM2NkMmIiLCJpYXQiOjE2NTYxNTk1MzF9.7wd0_JtNvLxCdK8EBRTQGyi0NqAJMIpkTKkCUbbPXpY

{
  "title": "Go To Statement Considered Harmful",
  "author": "Edsger W. Dijkstra",
  "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
  "likes": 5
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "mluukkai",
  "password": "123456"
}

# ###
# DELETE http://localhost:3003/api/blogs/5a422aa71b54a676234d17f9
# Content-Type: application/json